/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyClass */

#ifndef _Included_MyClass
#define _Included_MyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyClass
 * Method:    printNativeAddress
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyClass_printNativeAddress
  (JNIEnv *, jobject);

/*
 * Class:     MyClass
 * Method:    getNativeAddress
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_MyClass_getNativeAddress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
